// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Email     string  `json:"email"`
	JobTitle  *string `json:"jobTitle,omitempty"`
}

type FilterInput struct {
	ID        *string   `json:"id,omitempty"`
	FirstName []*string `json:"firstName,omitempty"`
	LastName  []string  `json:"lastName,omitempty"`
	Email     []string  `json:"email,omitempty"`
	JobTitle  []*string `json:"jobTitle,omitempty"`
	CreateAt  *string   `json:"createAt,omitempty"`
}
