// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FilterInput struct {
	ID        *string `json:"id,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	JobTitle  *string `json:"jobTitle,omitempty"`
	CreateAt  *string `json:"createAt,omitempty"`
}

type UserFeedback struct {
	ID        *string `json:"id,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	JobTitle  *string `json:"jobTitle,omitempty"`
	Feedback  *string `json:"feedback,omitempty"`
	CreateAt  *string `json:"createAt,omitempty"`
}

type UserFeedbackInput struct {
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Email     string  `json:"email"`
	JobTitle  *string `json:"jobTitle,omitempty"`
	Feedback  string  `json:"feedback"`
}
