services:
  postgres_db:
    # Official Postgres image from DockerHub (we use the last version)
    image: "postgres:14.1-alpine"
    container_name: postgres_db
    restart: always

    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    ports:
      - "5434:5432"

    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: feedback # The PostgreSQL default database (automatically created at first launch)

    ####
    ## If you want to use a `.env` file, please comment the `environment` section.
    ####

    # The `env_file` tag allows us to declare an environment file
    #env_file:
    #  - .env # The name of your environment file (the one at the repository root)

    ####
    ## If you want to persist the database data, please uncomment the lines below.
    ####

    # The `volumes` tag allows us to share a folder with our container.
    # Its syntax is as follows: [folder path on our machine]:[folder path to retrieve in the container]
    volumes:
      # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path.
      # It means that every time the repository is modifying the data inside
      # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`.
      # You don't need to create the `db-data` folder. Docker Compose will do it for you.
      # if we need to inspect the location of the volume we can use docker volume inspect db-data
      - ./postgresql/data//:/var/lib/postgresql/data/
    networks:
      datapipe:
  kafka:
    image: lensesio/fast-data-dev:3.9.0
    hostname: kafka
    environment:
      ADV_HOST: kafka
      RUNNING_SAMPLEDATA: 1
      RUNTESTS: 0
      # The next three variables are required if you want to have Kafka
      # available at the host for local development. They are tailored to KRaft
      # fast-data-dev (3.9.x or later). The broker will be available at localhost:9092.
      KAFKA_LISTENERS: PLAINTEXT://:9092,DOCKERCOMPOSE://:19092,CONTROLLER://:16062
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKERCOMPOSE://kafka:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        DOCKERCOMPOSE:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,
        SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      # Makes things a little lighter
      DISABLE: debezium-mongodb,debezium-mysql,debezium-postgres,debezium-sqlserver,debezium-jdbc
    # These are the ports for Kafka and Schema Registry. You can disable them if
    # you don't need to access Kafka from your host.
    ports:
      - 9092:9092
      - 8081:8081
      - 8083:8083
      - 3030:3030
    networks:
      datapipe:
    volumes:
      - data-kafka:/data
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.6.0
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:19092
      - LOGGING_LEVEL_ROOT=error
      - LOGGING_LEVEL_COM_PROVECTUS=error
      - KAFKA_CLUSTERS_0_JMXPORT=9997
      - DYNAMIC_CONFIG_ENABLED=true
    networks:
      datapipe:
    ports:
      - '9019:8080'
  graphql-service:
    container_name: graphql-service
    build:
      context: ../graphql-service
      dockerfile: ../graphql-service/Dockerfile
    depends_on:
      - kafka
      - postgres_db
    ports:
        - '4000:4000'
    environment:
      - LOG_LEVEL=debug
      - PORT=:4000
      - ENVIRONMENT=dev
      - KAFKA_BROKER=kafka:19092
      - KAFKA_TOPIC=data-pipe
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=feedback
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - MIGRATIONS_PATH=/app/migrations
    networks:
      datapipe:
    volumes:
      - "./db/feedback.sqlite:/feedback.sqlite"
  rest-service:
    container_name: rest-service
    build:
      context: ../rest-service
      dockerfile: ../rest-service/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - LOG_LEVEL=debug
      - PORT=:8080
      - ENVIRONMENT=dev
      - DB_FILE=email.sqlite
    networks:
      datapipe:
    volumes:
      - "./db/email.sqlite:/email.sqlite"
  benthos:
    container_name: benthos
    image: jeffail/benthos:4.7.0
    command:
       - -c
       - config.yaml
    depends_on:
      - rest-service
      - kafka
    volumes:
      - "./benthos/kafka-consumer.yaml:/config.yaml"
    networks:
      datapipe:
volumes:
  data-kafka:
    driver: local
networks:
  datapipe:
    driver: bridge
